version: '3.8'

services:
  sidekiq-metrics:
    build:
      context: .
      dockerfile: Dockerfile
    image: sidekiq-metrics:latest
    platform: linux/amd64
    environment:
      - REDIS_ADDR=redis:6379
      - REDIS_PASSWORD=
      - REDIS_DB=0
    depends_on:
      - redis
    command: ["/app/sidekiq-metrics"]

  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"
